### ISSUE TITLE
Bad rendering of "a" in small sizes on Windows

### ISSUE THREAD

**Issue by fat32** [uswds/public-sans#24] opened 2019-03-19 04:07 UTC
Screenshot of the issue: https://i.imgur.com/nrNgvX4.png

**Comment by stphnwlkr** [comment] 2019-03-19 10:37
We have seen this too, but only on some computers. I haven't been able to determine the cause, but it appears to be related to some policy that is pushed to those machines. One person sees it and the person next to them does not.

**Comment by thisisdano** [comment] 2019-03-19 17:03
I'll look into this — it's likely some kind of hinting error affected by Cleartype settings, but it may be hard to track down the right fix.

**Comment by fat32** [comment] 2019-03-20 19:44
I see this on two separate Windows setups:
Windows 10 at work,
Windows 7 at home (I don't remember that I did any ClearType tuning)

**Comment by thisisdano** [comment] 2019-03-21 17:50
I've been able to reproduce this, so hopefully I'll be able to find my way to a fix soon.

**Comment by thisisdano** [comment] 2019-03-21 17:57
@fat32 @stphnwlkr Can you look at the font rendering on this page and let me know if it shows the same mangled glyphs? Are there any other glyphs that have poor rendering?

https://federalist-proxy.app.cloud.gov/site/uswds/public-sans/

**Comment by stphnwlkr** [comment] 2019-03-21 19:44
I have only seen the issue as a result of others sharing the information. Interestingly, testing that site now...IE renders as Times New Roman inside the VA (flashed TNR externally before rendering), Chrome and Firefox no issues.

**Comment by thisisdano** [comment] 2019-03-21 20:29
The site linked above does not include the `eot` version of the face, which I understand to be necessary only for IE6-9. But if the face isn't rendering for you @stphnwlkr (and I assume you're using something more current than IE9) then that's not good.

**Comment by stphnwlkr** [comment] 2019-03-21 20:37
I am using IE 11 and I verified it didn't get downgraded. When I look at the dev tools, it is not attempting to load the fonts ... must be a VA thing

**Comment by thisisdano** [comment] 2019-03-21 20:38
Hm, but it _does_ load for... say v2.designsystem.digital.gov?

**Comment by thisisdano** [comment] 2019-03-21 20:40
This is the same specimen site, except with `eot` fronts in the `@font-face` rule: 
https://federalist-proxy.app.cloud.gov/preview/uswds/public-sans/dw-test-eot/

@stphnwlkr Does it load for you?

**Comment by thisisdano** [comment] 2019-03-21 20:54
For reference, this is a screenshot of v2.designsystem.digital.gov from a Windows 10 / IE 11 instance via saucelabs. (The result is the same in Edge browsers.) Note the `a` characters that descend below the baseline:

<img width="820" alt="Screen Shot 2019-03-21 at 1 46 01 PM" src="https://user-images.githubusercontent.com/11464021/54783884-c49e2700-4bdf-11e9-9d71-e11aeb9c9caf.png">

But I don't see similar output from the Public Sans specimen site — at least nothing as dramatic:
https://federalist-proxy.app.cloud.gov/preview/uswds/public-sans/dw-test-eot/

<img width="746" alt="Screen Shot 2019-03-21 at 1 51 08 PM" src="https://user-images.githubusercontent.com/11464021/54784268-a127ac00-4be0-11e9-9aae-506dd2642f83.png">

I'd hope that a little sleuthing should get to a fix...

**Comment by stphnwlkr** [comment] 2019-03-21 21:12
VA system on Win 7 is not rendering anything I think it is a VA configuration issue. The V2 site works although the layout is not quite right (header and footer). My EHRM site (www.ehrm.va.gov) which is V2 beta 5 with Public Sans works fine.

**Comment by thisisdano** [comment] 2019-03-21 21:41
So the more recent version of Public Sans has this render error:
https://federalist-proxy.app.cloud.gov/preview/uswds/public-sans/18f-pages/

But the older version on the `master` branch does not:
https://federalist-proxy.app.cloud.gov/site/uswds/public-sans/

I ought to be able to work with that.

@stphnwlkr Header layout better here? https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-font-do-si-do/

**Comment by stphnwlkr** [comment] 2019-03-21 21:44
Layout is much better ... thought I was in Chrome for a second.

**Comment by stphnwlkr** [comment] 2019-03-21 21:48
And yes, master is working fine.

**Comment by thisisdano** [comment] 2019-03-21 23:35
Updated fonts in action here: https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-font-do-si-do/

<img width="813" alt="Screen Shot 2019-03-21 at 4 33 32 PM" src="https://user-images.githubusercontent.com/11464021/54791465-3d5cad80-4bf7-11e9-9e3e-9d0e48ab3d31.png">


Looks better in my testing. What do you see @fat32 and @stphnwlkr ?

**Comment by stphnwlkr** [comment] 2019-03-22 00:06
Looking good on the VA system

**Comment by thisisdano** [comment] 2019-03-23 21:42
Fixed in https://github.com/uswds/public-sans/pull/27

**Closed by thisisdano** 2019-03-23 21:42 UTC
